# Generated by Django 5.0.7 on 2024-08-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moviestore", "0004_alter_actor_options_alter_director_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.ManyToManyField(to="moviestore.genre"),
        ),
    ]
