# Generated by Django 5.0.7 on 2024-08-01 20:19

import movie.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actors',
            new_name='actor',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie/images', validators=[movie.validators.validate_file_size]),
        ),
    ]
